### ISSUE TITLE
task templatecache not worked!

### ISSUE THREAD

**Issue by lsaturn** [flavordaaave/ionic-better-structure#2] opened 2015-11-19 00:07 UTC
because clean-code task has something wrong, if i modify 'clean' =>
function clean(path) {
  log('Cleaning: ' + $.util.colors.blue(path));
  del(path);
}
it worked.
am i somethong wrong?

**Comment by davidruisinger** [comment] 2015-11-19 09:35
Hey,
`gulp templatecache` as well as `gulp clean-code` are still working for me.
Could you post your terminal output?

**Comment by lsaturn** [comment] 2015-11-20 04:01
gulp templatecache
[12:00:41] Using gulpfile ~/Desktop/work/MabaoyuEnv/MaBaoyu/js_modules/matongxue.mobile.frontend/gulpfile.js
[12:00:41] Starting 'clean-code'...
[12:00:41] Cleaning: ./src/.tmp/**/*.js,./www/js/**/_.js,./www/__/_.html

stopped without output
wow, i used "del": "^2.1.0",

**Comment by davidruisinger** [comment] 2016-01-04 12:15
Sorry for not responding earlier, lots of work over the last weeks.
Have you tried using `"del": "^1.2.0"` in your package.json? (do a `npm install` after changing version)´

**Comment by davidruisinger** [comment] 2016-05-25 20:47
I'm closing this for now since I cannot reproduce it (anymore). Please feel free to re-open/comment if the issue is still not fixed for you.

**Closed as completed by davidruisinger** 2016-05-25 20:47 UTC
